#### membersonly RESTful api example ####
:baseurl = http://localhost:5000

# GET members
GET :baseurl/members
#

# GET member by id
GET :baseurl/members/3
#
# POST add member
POST :baseurl/members
Content-Type: application/json
{
        "name": "testuser4",
        "email": "testuser@foofoo.ca",
        "level": "bronze"
}
#

# POST add member
POST :baseurl/members
Content-Type: application/json
{
        "name": "testuser2",
        "email": "testuser2@foo.ca",
        "level": "gold"
}
#

# update member with PUT (no missing values)
PUT :baseurl/members/3
Content-Type: application/json
{
        "name": "testuser2",
        "email": "testyboy@foo.ca",
        "level": "platinum"
}

# update member with PUT (missing values)
PUT :baseurl/members/3
Content-Type: application/json
{
        "name": "testuser2",
        "level": "platinum"
}

# update member with PATCH
PATCH :baseurl/members/3
Content-Type: application/json
{
        "name": "FooFoo Beanz"
}
# update member with PATCH
PATCH :baseurl/members/3
Content-Type: application/json
{
        "level": "silver"
}

# delete member by ID
DELETE :baseurl/members/3