#### membersonly RESTful api example ####
:baseurl = http://localhost:5000

# GET members
GET :baseurl/members
#

# GET member by id
GET :baseurl/members/14

# POST add member
POST :baseurl/members
Content-Type: application/json
{
        "name": "testuser",
        "email": "testuser@foo.ca",
        "level": "platinum"
}
#

# POST add member
POST :baseurl/members
Content-Type: application/json
{
        "name": "testuser2",
        "email": "testuser2@foo.ca",
        "level": "gold"
}
#
# update member with PUT
PUT :baseurl/members/14

# update member with PATCH
PATCH :baseurl/members/14

# delete member by ID
DELETE :baseurl/members/14